edgexfoundry/sample-service

Jenkinsfile

update mock stage

---

Jenkinsfile

remove env debug

---

docker/Dockerfile

remove unused dependencies

---

Jenkinsfile

Add demo echo

---

Jenkinsfile

Now using declarative for more structure and readability.

refactor scripted pipeline to declarative pipeline

---

Jenkinsfile

add edgeXSetupEnvironment to enable git semver specific vars

---

Jenkinsfile
docker/Dockerfile

pin to Go version 1.11.8

---

Jenkinsfile

Want to test a few things with this PR:
1) git semver tag|bump|push functionality 
2) when conditional on semver tag|bump|push stages

Test Semver stages using when expression

---

Jenkinsfile

Want to test a few things with this PR:
1. git semver tag|bump|push functionality
2. revert when conditional on semver tag|bump|push stages to what it was before

Test Semver revert to original when expression

---

Jenkinsfile.sandbox

add sandbox pipeline file with custom Library include

---

Jenkinsfile.sandbox

update to v1.0.19

---

Jenkinsfile.sandbox

update to use experimental egp

---

Dockerfile
Jenkinsfile

Signed-off-by: Venkata Lakshmi Dhatri Penna <venkata.lakshmi.dhatrix.penna@intel.com>
Test Links :
N/A
NO

Add Dockerfile

---

Jenkinsfile.sandbox

Add git information

---

Jenkinsfile.sandbox

revert git info code

---

.github/pull_request_template.md

Signed-off-by: James Gregg <james.r.gregg@intel.com>
Update as per decision in Architect's meeting 06/15/2020 to include dependencies question
Test Links :

docs: Update PR Template

---

Jenkinsfile.sandbox

Functional testing for build commits

---

Jenkinsfile

build(test): [4.1.3,stable] Test build commit in production Jenkins

---

Jenkinsfile
Jenkinsfile.sandbox

build(test): [4.1.3,stable] Test build commit in production Jenkins 2

---

Jenkinsfile

build(test): [4.1.3,stable] Test build commit in production Jenkins 3

---

Jenkinsfile

build(test): [4.1.3,stable] Test build commit in production Jenkins 4

---

Jenkinsfile

build(test): [4.1.4,stable] Test build commit in production Jenkins 5

---

Jenkinsfile

build(test): [4.1.5,stable] Test build commit in production Jenkins 5

---

Jenkinsfile

revert to experimental lib version

---

Jenkinsfile

feat: update to Golang 1.15

---

Jenkinsfile

Remove build experimental

---

Jenkinsfile

Add build experimental

---

Jenkinsfile

Add build experimental - fix bug

---

Jenkinsfile.save

edgeXSemver functional testing

---

Jenkinsfile

ci: testing for codecov

---

Jenkinsfile
Jenkinsfile.sandbox

ci: update edgex-global-pipelines tag

---

Makefile

Add race condition flag to be consistent with other repos.
Test Links :

ci: add -race condition to go test command

---

Jenkinsfile

Make fake update

---

README.md

Reorder badges

---

README.md

created via automation. this is a test - ignore

this is a test - ignore

---

Jenkinsfile

ci: testing main changes

---

Dockerfile

Changes related to Go 1.17 and cache optimizations

ci: Go 1.17 Dockerfile related changes

---

Jenkinsfile

ci: testing new Snyk features

---

Jenkinsfile

ci: reset library back to experimental

---

go.mod
vendor/modules.txt

ci: fix inconsistent dependencies

---

Dockerfile
Jenkinsfile
bin/test-attribution-txt.sh
go.mod

feat: move to Go 1.18

---

.github/workflows/release.yml

fix: release yaml syntax

---

.github/workflows/release.yml

fix: only create releases for patch releases

---

CHANGELOG.md

docs: add CHANGELOG for next release v5.1.5

---

.github/workflows/release.yml

ci: update to use stable branch on release
